"""empty message

Revision ID: 2441f858fd83
Revises: 1ecf77eec85f
Create Date: 2024-09-20 02:23:42.207837

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2441f858fd83'
down_revision: Union[str, None] = '1ecf77eec85f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_session', sa.Column('user_agent', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refresh_session', 'user_agent')
    # ### end Alembic commands ###
