"""empty message

Revision ID: 0b78908d5045
Revises: 2441f858fd83
Create Date: 2024-09-24 15:02:44.143253

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0b78908d5045'
down_revision: Union[str, None] = '2441f858fd83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('photo_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'photo_url')
    # ### end Alembic commands ###
