"""empty message

Revision ID: 1ecf77eec85f
Revises: 23d0f7473ca5
Create Date: 2024-09-20 02:09:55.318069

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1ecf77eec85f'
down_revision: Union[str, None] = '23d0f7473ca5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_sessions', sa.Column('user_agent', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_sessions', 'user_agent')
    # ### end Alembic commands ###
